#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34003
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaMarva1._0
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="C:\\Source\\Repos\\LaMarca1.0\\LaMarca1.0\\Mordor.sdf")]
	public partial class MordorContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertArmaduras(Armaduras instance);
    partial void UpdateArmaduras(Armaduras instance);
    partial void DeleteArmaduras(Armaduras instance);
    partial void InsertArmas(Armas instance);
    partial void UpdateArmas(Armas instance);
    partial void DeleteArmas(Armas instance);
    partial void InsertConjurosArcanos(ConjurosArcanos instance);
    partial void UpdateConjurosArcanos(ConjurosArcanos instance);
    partial void DeleteConjurosArcanos(ConjurosArcanos instance);
    partial void InsertConjurosDivinos(ConjurosDivinos instance);
    partial void UpdateConjurosDivinos(ConjurosDivinos instance);
    partial void DeleteConjurosDivinos(ConjurosDivinos instance);
    partial void InsertCriaturas(Criaturas instance);
    partial void UpdateCriaturas(Criaturas instance);
    partial void DeleteCriaturas(Criaturas instance);
    partial void InsertCriaturasPersonalizadas(CriaturasPersonalizadas instance);
    partial void UpdateCriaturasPersonalizadas(CriaturasPersonalizadas instance);
    partial void DeleteCriaturasPersonalizadas(CriaturasPersonalizadas instance);
    partial void InsertEquipo(Equipo instance);
    partial void UpdateEquipo(Equipo instance);
    partial void DeleteEquipo(Equipo instance);
    partial void InsertLugares(Lugares instance);
    partial void UpdateLugares(Lugares instance);
    partial void DeleteLugares(Lugares instance);
    partial void InsertPnj(Pnj instance);
    partial void UpdatePnj(Pnj instance);
    partial void DeletePnj(Pnj instance);
    partial void InsertTransporte(Transporte instance);
    partial void UpdateTransporte(Transporte instance);
    partial void DeleteTransporte(Transporte instance);
    #endregion
		
		public MordorContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MordorContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MordorContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MordorContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Armaduras> Armaduras
		{
			get
			{
				return this.GetTable<Armaduras>();
			}
		}
		
		public System.Data.Linq.Table<Armas> Armas
		{
			get
			{
				return this.GetTable<Armas>();
			}
		}
		
		public System.Data.Linq.Table<ConjurosArcanos> ConjurosArcanos
		{
			get
			{
				return this.GetTable<ConjurosArcanos>();
			}
		}
		
		public System.Data.Linq.Table<ConjurosDivinos> ConjurosDivinos
		{
			get
			{
				return this.GetTable<ConjurosDivinos>();
			}
		}
		
		public System.Data.Linq.Table<Criaturas> Criaturas
		{
			get
			{
				return this.GetTable<Criaturas>();
			}
		}
		
		public System.Data.Linq.Table<CriaturasPersonalizadas> CriaturasPersonalizadas
		{
			get
			{
				return this.GetTable<CriaturasPersonalizadas>();
			}
		}
		
		public System.Data.Linq.Table<Equipo> Equipo
		{
			get
			{
				return this.GetTable<Equipo>();
			}
		}
		
		public System.Data.Linq.Table<Lugares> Lugares
		{
			get
			{
				return this.GetTable<Lugares>();
			}
		}
		
		public System.Data.Linq.Table<Pnj> Pnj
		{
			get
			{
				return this.GetTable<Pnj>();
			}
		}
		
		public System.Data.Linq.Table<Transporte> Transporte
		{
			get
			{
				return this.GetTable<Transporte>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class Armaduras : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Armadura_Id;
		
		private string _Armadura_Nombre;
		
		private System.Nullable<long> _Armadura_Coste;
		
		private System.Nullable<int> _Armadura_CA;
		
		private System.Nullable<double> _Armadura_Peso;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnArmadura_IdChanging(int value);
    partial void OnArmadura_IdChanged();
    partial void OnArmadura_NombreChanging(string value);
    partial void OnArmadura_NombreChanged();
    partial void OnArmadura_CosteChanging(System.Nullable<long> value);
    partial void OnArmadura_CosteChanged();
    partial void OnArmadura_CAChanging(System.Nullable<int> value);
    partial void OnArmadura_CAChanged();
    partial void OnArmadura_PesoChanging(System.Nullable<double> value);
    partial void OnArmadura_PesoChanged();
    #endregion
		
		public Armaduras()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Armadura_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Armadura_Id
		{
			get
			{
				return this._Armadura_Id;
			}
			set
			{
				if ((this._Armadura_Id != value))
				{
					this.OnArmadura_IdChanging(value);
					this.SendPropertyChanging();
					this._Armadura_Id = value;
					this.SendPropertyChanged("Armadura_Id");
					this.OnArmadura_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Armadura_Nombre", DbType="NVarChar(50)")]
		public string Armadura_Nombre
		{
			get
			{
				return this._Armadura_Nombre;
			}
			set
			{
				if ((this._Armadura_Nombre != value))
				{
					this.OnArmadura_NombreChanging(value);
					this.SendPropertyChanging();
					this._Armadura_Nombre = value;
					this.SendPropertyChanged("Armadura_Nombre");
					this.OnArmadura_NombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Armadura_Coste", DbType="BigInt")]
		public System.Nullable<long> Armadura_Coste
		{
			get
			{
				return this._Armadura_Coste;
			}
			set
			{
				if ((this._Armadura_Coste != value))
				{
					this.OnArmadura_CosteChanging(value);
					this.SendPropertyChanging();
					this._Armadura_Coste = value;
					this.SendPropertyChanged("Armadura_Coste");
					this.OnArmadura_CosteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Armadura_CA", DbType="Int")]
		public System.Nullable<int> Armadura_CA
		{
			get
			{
				return this._Armadura_CA;
			}
			set
			{
				if ((this._Armadura_CA != value))
				{
					this.OnArmadura_CAChanging(value);
					this.SendPropertyChanging();
					this._Armadura_CA = value;
					this.SendPropertyChanged("Armadura_CA");
					this.OnArmadura_CAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Armadura_Peso", DbType="Float")]
		public System.Nullable<double> Armadura_Peso
		{
			get
			{
				return this._Armadura_Peso;
			}
			set
			{
				if ((this._Armadura_Peso != value))
				{
					this.OnArmadura_PesoChanging(value);
					this.SendPropertyChanging();
					this._Armadura_Peso = value;
					this.SendPropertyChanged("Armadura_Peso");
					this.OnArmadura_PesoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class Armas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Arma_Id;
		
		private string _Arma_Nombre;
		
		private System.Nullable<long> _Arma_Coste;
		
		private string _Arma_Danio;
		
		private System.Nullable<double> _Arma_Peso;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnArma_IdChanging(int value);
    partial void OnArma_IdChanged();
    partial void OnArma_NombreChanging(string value);
    partial void OnArma_NombreChanged();
    partial void OnArma_CosteChanging(System.Nullable<long> value);
    partial void OnArma_CosteChanged();
    partial void OnArma_DanioChanging(string value);
    partial void OnArma_DanioChanged();
    partial void OnArma_PesoChanging(System.Nullable<double> value);
    partial void OnArma_PesoChanged();
    #endregion
		
		public Armas()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Arma_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Arma_Id
		{
			get
			{
				return this._Arma_Id;
			}
			set
			{
				if ((this._Arma_Id != value))
				{
					this.OnArma_IdChanging(value);
					this.SendPropertyChanging();
					this._Arma_Id = value;
					this.SendPropertyChanged("Arma_Id");
					this.OnArma_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Arma_Nombre", DbType="NVarChar(50)")]
		public string Arma_Nombre
		{
			get
			{
				return this._Arma_Nombre;
			}
			set
			{
				if ((this._Arma_Nombre != value))
				{
					this.OnArma_NombreChanging(value);
					this.SendPropertyChanging();
					this._Arma_Nombre = value;
					this.SendPropertyChanged("Arma_Nombre");
					this.OnArma_NombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Arma_Coste", DbType="BigInt")]
		public System.Nullable<long> Arma_Coste
		{
			get
			{
				return this._Arma_Coste;
			}
			set
			{
				if ((this._Arma_Coste != value))
				{
					this.OnArma_CosteChanging(value);
					this.SendPropertyChanging();
					this._Arma_Coste = value;
					this.SendPropertyChanged("Arma_Coste");
					this.OnArma_CosteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Arma_Danio", DbType="NVarChar(10)")]
		public string Arma_Danio
		{
			get
			{
				return this._Arma_Danio;
			}
			set
			{
				if ((this._Arma_Danio != value))
				{
					this.OnArma_DanioChanging(value);
					this.SendPropertyChanging();
					this._Arma_Danio = value;
					this.SendPropertyChanged("Arma_Danio");
					this.OnArma_DanioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Arma_Peso", DbType="Float")]
		public System.Nullable<double> Arma_Peso
		{
			get
			{
				return this._Arma_Peso;
			}
			set
			{
				if ((this._Arma_Peso != value))
				{
					this.OnArma_PesoChanging(value);
					this.SendPropertyChanging();
					this._Arma_Peso = value;
					this.SendPropertyChanged("Arma_Peso");
					this.OnArma_PesoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class ConjurosArcanos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _C_Arcano_Id;
		
		private System.Nullable<int> _C_Arcano_Nivel;
		
		private string _C_Arcano_Nombre;
		
		private string _C_Arcano_Alcance;
		
		private string _C_arcano_Duracion;
		
		private string _C_Arcano_Descripcion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnC_Arcano_IdChanging(int value);
    partial void OnC_Arcano_IdChanged();
    partial void OnC_Arcano_NivelChanging(System.Nullable<int> value);
    partial void OnC_Arcano_NivelChanged();
    partial void OnC_Arcano_NombreChanging(string value);
    partial void OnC_Arcano_NombreChanged();
    partial void OnC_Arcano_AlcanceChanging(string value);
    partial void OnC_Arcano_AlcanceChanged();
    partial void OnC_arcano_DuracionChanging(string value);
    partial void OnC_arcano_DuracionChanged();
    partial void OnC_Arcano_DescripcionChanging(string value);
    partial void OnC_Arcano_DescripcionChanged();
    #endregion
		
		public ConjurosArcanos()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Arcano_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int C_Arcano_Id
		{
			get
			{
				return this._C_Arcano_Id;
			}
			set
			{
				if ((this._C_Arcano_Id != value))
				{
					this.OnC_Arcano_IdChanging(value);
					this.SendPropertyChanging();
					this._C_Arcano_Id = value;
					this.SendPropertyChanged("C_Arcano_Id");
					this.OnC_Arcano_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Arcano_Nivel", DbType="Int")]
		public System.Nullable<int> C_Arcano_Nivel
		{
			get
			{
				return this._C_Arcano_Nivel;
			}
			set
			{
				if ((this._C_Arcano_Nivel != value))
				{
					this.OnC_Arcano_NivelChanging(value);
					this.SendPropertyChanging();
					this._C_Arcano_Nivel = value;
					this.SendPropertyChanged("C_Arcano_Nivel");
					this.OnC_Arcano_NivelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Arcano_Nombre", DbType="NVarChar(50)")]
		public string C_Arcano_Nombre
		{
			get
			{
				return this._C_Arcano_Nombre;
			}
			set
			{
				if ((this._C_Arcano_Nombre != value))
				{
					this.OnC_Arcano_NombreChanging(value);
					this.SendPropertyChanging();
					this._C_Arcano_Nombre = value;
					this.SendPropertyChanged("C_Arcano_Nombre");
					this.OnC_Arcano_NombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Arcano_Alcance", DbType="NVarChar(50)")]
		public string C_Arcano_Alcance
		{
			get
			{
				return this._C_Arcano_Alcance;
			}
			set
			{
				if ((this._C_Arcano_Alcance != value))
				{
					this.OnC_Arcano_AlcanceChanging(value);
					this.SendPropertyChanging();
					this._C_Arcano_Alcance = value;
					this.SendPropertyChanged("C_Arcano_Alcance");
					this.OnC_Arcano_AlcanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_arcano_Duracion", DbType="NVarChar(50)")]
		public string C_arcano_Duracion
		{
			get
			{
				return this._C_arcano_Duracion;
			}
			set
			{
				if ((this._C_arcano_Duracion != value))
				{
					this.OnC_arcano_DuracionChanging(value);
					this.SendPropertyChanging();
					this._C_arcano_Duracion = value;
					this.SendPropertyChanged("C_arcano_Duracion");
					this.OnC_arcano_DuracionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Arcano_Descripcion", DbType="NVarChar(200)")]
		public string C_Arcano_Descripcion
		{
			get
			{
				return this._C_Arcano_Descripcion;
			}
			set
			{
				if ((this._C_Arcano_Descripcion != value))
				{
					this.OnC_Arcano_DescripcionChanging(value);
					this.SendPropertyChanging();
					this._C_Arcano_Descripcion = value;
					this.SendPropertyChanged("C_Arcano_Descripcion");
					this.OnC_Arcano_DescripcionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class ConjurosDivinos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _C_Divino_Id;
		
		private System.Nullable<int> _C_Divino_Nivel;
		
		private string _C_Divino_Nombre;
		
		private string _C_Divino_Alcance;
		
		private string _C_Divino_Duracion;
		
		private string _C_Divino_Descripcion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnC_Divino_IdChanging(int value);
    partial void OnC_Divino_IdChanged();
    partial void OnC_Divino_NivelChanging(System.Nullable<int> value);
    partial void OnC_Divino_NivelChanged();
    partial void OnC_Divino_NombreChanging(string value);
    partial void OnC_Divino_NombreChanged();
    partial void OnC_Divino_AlcanceChanging(string value);
    partial void OnC_Divino_AlcanceChanged();
    partial void OnC_Divino_DuracionChanging(string value);
    partial void OnC_Divino_DuracionChanged();
    partial void OnC_Divino_DescripcionChanging(string value);
    partial void OnC_Divino_DescripcionChanged();
    #endregion
		
		public ConjurosDivinos()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Divino_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int C_Divino_Id
		{
			get
			{
				return this._C_Divino_Id;
			}
			set
			{
				if ((this._C_Divino_Id != value))
				{
					this.OnC_Divino_IdChanging(value);
					this.SendPropertyChanging();
					this._C_Divino_Id = value;
					this.SendPropertyChanged("C_Divino_Id");
					this.OnC_Divino_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Divino_Nivel", DbType="Int")]
		public System.Nullable<int> C_Divino_Nivel
		{
			get
			{
				return this._C_Divino_Nivel;
			}
			set
			{
				if ((this._C_Divino_Nivel != value))
				{
					this.OnC_Divino_NivelChanging(value);
					this.SendPropertyChanging();
					this._C_Divino_Nivel = value;
					this.SendPropertyChanged("C_Divino_Nivel");
					this.OnC_Divino_NivelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Divino_Nombre", DbType="NVarChar(50)")]
		public string C_Divino_Nombre
		{
			get
			{
				return this._C_Divino_Nombre;
			}
			set
			{
				if ((this._C_Divino_Nombre != value))
				{
					this.OnC_Divino_NombreChanging(value);
					this.SendPropertyChanging();
					this._C_Divino_Nombre = value;
					this.SendPropertyChanged("C_Divino_Nombre");
					this.OnC_Divino_NombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Divino_Alcance", DbType="NVarChar(50)")]
		public string C_Divino_Alcance
		{
			get
			{
				return this._C_Divino_Alcance;
			}
			set
			{
				if ((this._C_Divino_Alcance != value))
				{
					this.OnC_Divino_AlcanceChanging(value);
					this.SendPropertyChanging();
					this._C_Divino_Alcance = value;
					this.SendPropertyChanged("C_Divino_Alcance");
					this.OnC_Divino_AlcanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Divino_Duracion", DbType="NVarChar(50)")]
		public string C_Divino_Duracion
		{
			get
			{
				return this._C_Divino_Duracion;
			}
			set
			{
				if ((this._C_Divino_Duracion != value))
				{
					this.OnC_Divino_DuracionChanging(value);
					this.SendPropertyChanging();
					this._C_Divino_Duracion = value;
					this.SendPropertyChanged("C_Divino_Duracion");
					this.OnC_Divino_DuracionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Divino_Descripcion", DbType="NVarChar(200)")]
		public string C_Divino_Descripcion
		{
			get
			{
				return this._C_Divino_Descripcion;
			}
			set
			{
				if ((this._C_Divino_Descripcion != value))
				{
					this.OnC_Divino_DescripcionChanging(value);
					this.SendPropertyChanging();
					this._C_Divino_Descripcion = value;
					this.SendPropertyChanged("C_Divino_Descripcion");
					this.OnC_Divino_DescripcionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class Criaturas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Criatura_Id;
		
		private string _Criatura_Nombre;
		
		private System.Nullable<long> _Criatura_CA_Neg;
		
		private System.Nullable<long> _Criatura_CA_Pos;
		
		private System.Nullable<long> _Criatura_Vida_Media;
		
		private System.Nullable<long> _Criatura_Vida_Max;
		
		private System.Nullable<int> _Criatura_Ataque;
		
		private string _Criatura_Ataque_I;
		
		private string _Criatura_Ataque_II;
		
		private System.Nullable<int> _Criatura_S_VenMuer;
		
		private System.Nullable<int> _Criatura_S_Varitas;
		
		private System.Nullable<int> _Criatura_S_PetrifParal;
		
		private System.Nullable<int> _Criatura_S_AlienDrag;
		
		private System.Nullable<int> _Criatura_S_Sortilegios;
		
		private System.Nullable<long> _Criatura_Mov;
		
		private System.Nullable<int> _Criatura_Moral;
		
		private System.Nullable<long> _Criatura_ValorTesoro;
		
		private string _Criatura_Alineam;
		
		private System.Nullable<long> _Criatura_ValorPX;
		
		private System.Nullable<int> _Criatura_DG;
		
		private string _Criatura_Habilidades_I;
		
		private string _Criatura_Habilidades_II;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCriatura_IdChanging(int value);
    partial void OnCriatura_IdChanged();
    partial void OnCriatura_NombreChanging(string value);
    partial void OnCriatura_NombreChanged();
    partial void OnCriatura_CA_NegChanging(System.Nullable<long> value);
    partial void OnCriatura_CA_NegChanged();
    partial void OnCriatura_CA_PosChanging(System.Nullable<long> value);
    partial void OnCriatura_CA_PosChanged();
    partial void OnCriatura_Vida_MediaChanging(System.Nullable<long> value);
    partial void OnCriatura_Vida_MediaChanged();
    partial void OnCriatura_Vida_MaxChanging(System.Nullable<long> value);
    partial void OnCriatura_Vida_MaxChanged();
    partial void OnCriatura_AtaqueChanging(System.Nullable<int> value);
    partial void OnCriatura_AtaqueChanged();
    partial void OnCriatura_Ataque_IChanging(string value);
    partial void OnCriatura_Ataque_IChanged();
    partial void OnCriatura_Ataque_IIChanging(string value);
    partial void OnCriatura_Ataque_IIChanged();
    partial void OnCriatura_S_VenMuerChanging(System.Nullable<int> value);
    partial void OnCriatura_S_VenMuerChanged();
    partial void OnCriatura_S_VaritasChanging(System.Nullable<int> value);
    partial void OnCriatura_S_VaritasChanged();
    partial void OnCriatura_S_PetrifParalChanging(System.Nullable<int> value);
    partial void OnCriatura_S_PetrifParalChanged();
    partial void OnCriatura_S_AlienDragChanging(System.Nullable<int> value);
    partial void OnCriatura_S_AlienDragChanged();
    partial void OnCriatura_S_SortilegiosChanging(System.Nullable<int> value);
    partial void OnCriatura_S_SortilegiosChanged();
    partial void OnCriatura_MovChanging(System.Nullable<long> value);
    partial void OnCriatura_MovChanged();
    partial void OnCriatura_MoralChanging(System.Nullable<int> value);
    partial void OnCriatura_MoralChanged();
    partial void OnCriatura_ValorTesoroChanging(System.Nullable<long> value);
    partial void OnCriatura_ValorTesoroChanged();
    partial void OnCriatura_AlineamChanging(string value);
    partial void OnCriatura_AlineamChanged();
    partial void OnCriatura_ValorPXChanging(System.Nullable<long> value);
    partial void OnCriatura_ValorPXChanged();
    partial void OnCriatura_DGChanging(System.Nullable<int> value);
    partial void OnCriatura_DGChanged();
    partial void OnCriatura_Habilidades_IChanging(string value);
    partial void OnCriatura_Habilidades_IChanged();
    partial void OnCriatura_Habilidades_IIChanging(string value);
    partial void OnCriatura_Habilidades_IIChanged();
    #endregion
		
		public Criaturas()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Criatura_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Criatura_Id
		{
			get
			{
				return this._Criatura_Id;
			}
			set
			{
				if ((this._Criatura_Id != value))
				{
					this.OnCriatura_IdChanging(value);
					this.SendPropertyChanging();
					this._Criatura_Id = value;
					this.SendPropertyChanged("Criatura_Id");
					this.OnCriatura_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Criatura_Nombre", DbType="NVarChar(50)")]
		public string Criatura_Nombre
		{
			get
			{
				return this._Criatura_Nombre;
			}
			set
			{
				if ((this._Criatura_Nombre != value))
				{
					this.OnCriatura_NombreChanging(value);
					this.SendPropertyChanging();
					this._Criatura_Nombre = value;
					this.SendPropertyChanged("Criatura_Nombre");
					this.OnCriatura_NombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Criatura_CA_Neg", DbType="BigInt")]
		public System.Nullable<long> Criatura_CA_Neg
		{
			get
			{
				return this._Criatura_CA_Neg;
			}
			set
			{
				if ((this._Criatura_CA_Neg != value))
				{
					this.OnCriatura_CA_NegChanging(value);
					this.SendPropertyChanging();
					this._Criatura_CA_Neg = value;
					this.SendPropertyChanged("Criatura_CA_Neg");
					this.OnCriatura_CA_NegChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Criatura_CA_Pos", DbType="BigInt")]
		public System.Nullable<long> Criatura_CA_Pos
		{
			get
			{
				return this._Criatura_CA_Pos;
			}
			set
			{
				if ((this._Criatura_CA_Pos != value))
				{
					this.OnCriatura_CA_PosChanging(value);
					this.SendPropertyChanging();
					this._Criatura_CA_Pos = value;
					this.SendPropertyChanged("Criatura_CA_Pos");
					this.OnCriatura_CA_PosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Criatura_Vida_Media", DbType="BigInt")]
		public System.Nullable<long> Criatura_Vida_Media
		{
			get
			{
				return this._Criatura_Vida_Media;
			}
			set
			{
				if ((this._Criatura_Vida_Media != value))
				{
					this.OnCriatura_Vida_MediaChanging(value);
					this.SendPropertyChanging();
					this._Criatura_Vida_Media = value;
					this.SendPropertyChanged("Criatura_Vida_Media");
					this.OnCriatura_Vida_MediaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Criatura_Vida_Max", DbType="BigInt")]
		public System.Nullable<long> Criatura_Vida_Max
		{
			get
			{
				return this._Criatura_Vida_Max;
			}
			set
			{
				if ((this._Criatura_Vida_Max != value))
				{
					this.OnCriatura_Vida_MaxChanging(value);
					this.SendPropertyChanging();
					this._Criatura_Vida_Max = value;
					this.SendPropertyChanged("Criatura_Vida_Max");
					this.OnCriatura_Vida_MaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Criatura_Ataque", DbType="Int")]
		public System.Nullable<int> Criatura_Ataque
		{
			get
			{
				return this._Criatura_Ataque;
			}
			set
			{
				if ((this._Criatura_Ataque != value))
				{
					this.OnCriatura_AtaqueChanging(value);
					this.SendPropertyChanging();
					this._Criatura_Ataque = value;
					this.SendPropertyChanged("Criatura_Ataque");
					this.OnCriatura_AtaqueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Criatura_Ataque_I", DbType="NVarChar(50)")]
		public string Criatura_Ataque_I
		{
			get
			{
				return this._Criatura_Ataque_I;
			}
			set
			{
				if ((this._Criatura_Ataque_I != value))
				{
					this.OnCriatura_Ataque_IChanging(value);
					this.SendPropertyChanging();
					this._Criatura_Ataque_I = value;
					this.SendPropertyChanged("Criatura_Ataque_I");
					this.OnCriatura_Ataque_IChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Criatura_Ataque_II", DbType="NVarChar(50)")]
		public string Criatura_Ataque_II
		{
			get
			{
				return this._Criatura_Ataque_II;
			}
			set
			{
				if ((this._Criatura_Ataque_II != value))
				{
					this.OnCriatura_Ataque_IIChanging(value);
					this.SendPropertyChanging();
					this._Criatura_Ataque_II = value;
					this.SendPropertyChanged("Criatura_Ataque_II");
					this.OnCriatura_Ataque_IIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Criatura_S_VenMuer", DbType="Int")]
		public System.Nullable<int> Criatura_S_VenMuer
		{
			get
			{
				return this._Criatura_S_VenMuer;
			}
			set
			{
				if ((this._Criatura_S_VenMuer != value))
				{
					this.OnCriatura_S_VenMuerChanging(value);
					this.SendPropertyChanging();
					this._Criatura_S_VenMuer = value;
					this.SendPropertyChanged("Criatura_S_VenMuer");
					this.OnCriatura_S_VenMuerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Criatura_S_Varitas", DbType="Int")]
		public System.Nullable<int> Criatura_S_Varitas
		{
			get
			{
				return this._Criatura_S_Varitas;
			}
			set
			{
				if ((this._Criatura_S_Varitas != value))
				{
					this.OnCriatura_S_VaritasChanging(value);
					this.SendPropertyChanging();
					this._Criatura_S_Varitas = value;
					this.SendPropertyChanged("Criatura_S_Varitas");
					this.OnCriatura_S_VaritasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Criatura_S_PetrifParal", DbType="Int")]
		public System.Nullable<int> Criatura_S_PetrifParal
		{
			get
			{
				return this._Criatura_S_PetrifParal;
			}
			set
			{
				if ((this._Criatura_S_PetrifParal != value))
				{
					this.OnCriatura_S_PetrifParalChanging(value);
					this.SendPropertyChanging();
					this._Criatura_S_PetrifParal = value;
					this.SendPropertyChanged("Criatura_S_PetrifParal");
					this.OnCriatura_S_PetrifParalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Criatura_S_AlienDrag", DbType="Int")]
		public System.Nullable<int> Criatura_S_AlienDrag
		{
			get
			{
				return this._Criatura_S_AlienDrag;
			}
			set
			{
				if ((this._Criatura_S_AlienDrag != value))
				{
					this.OnCriatura_S_AlienDragChanging(value);
					this.SendPropertyChanging();
					this._Criatura_S_AlienDrag = value;
					this.SendPropertyChanged("Criatura_S_AlienDrag");
					this.OnCriatura_S_AlienDragChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Criatura_S_Sortilegios", DbType="Int")]
		public System.Nullable<int> Criatura_S_Sortilegios
		{
			get
			{
				return this._Criatura_S_Sortilegios;
			}
			set
			{
				if ((this._Criatura_S_Sortilegios != value))
				{
					this.OnCriatura_S_SortilegiosChanging(value);
					this.SendPropertyChanging();
					this._Criatura_S_Sortilegios = value;
					this.SendPropertyChanged("Criatura_S_Sortilegios");
					this.OnCriatura_S_SortilegiosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Criatura_Mov", DbType="BigInt")]
		public System.Nullable<long> Criatura_Mov
		{
			get
			{
				return this._Criatura_Mov;
			}
			set
			{
				if ((this._Criatura_Mov != value))
				{
					this.OnCriatura_MovChanging(value);
					this.SendPropertyChanging();
					this._Criatura_Mov = value;
					this.SendPropertyChanged("Criatura_Mov");
					this.OnCriatura_MovChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Criatura_Moral", DbType="Int")]
		public System.Nullable<int> Criatura_Moral
		{
			get
			{
				return this._Criatura_Moral;
			}
			set
			{
				if ((this._Criatura_Moral != value))
				{
					this.OnCriatura_MoralChanging(value);
					this.SendPropertyChanging();
					this._Criatura_Moral = value;
					this.SendPropertyChanged("Criatura_Moral");
					this.OnCriatura_MoralChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Criatura_ValorTesoro", DbType="BigInt")]
		public System.Nullable<long> Criatura_ValorTesoro
		{
			get
			{
				return this._Criatura_ValorTesoro;
			}
			set
			{
				if ((this._Criatura_ValorTesoro != value))
				{
					this.OnCriatura_ValorTesoroChanging(value);
					this.SendPropertyChanging();
					this._Criatura_ValorTesoro = value;
					this.SendPropertyChanged("Criatura_ValorTesoro");
					this.OnCriatura_ValorTesoroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Criatura_Alineam", DbType="NVarChar(50)")]
		public string Criatura_Alineam
		{
			get
			{
				return this._Criatura_Alineam;
			}
			set
			{
				if ((this._Criatura_Alineam != value))
				{
					this.OnCriatura_AlineamChanging(value);
					this.SendPropertyChanging();
					this._Criatura_Alineam = value;
					this.SendPropertyChanged("Criatura_Alineam");
					this.OnCriatura_AlineamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Criatura_ValorPX", DbType="BigInt")]
		public System.Nullable<long> Criatura_ValorPX
		{
			get
			{
				return this._Criatura_ValorPX;
			}
			set
			{
				if ((this._Criatura_ValorPX != value))
				{
					this.OnCriatura_ValorPXChanging(value);
					this.SendPropertyChanging();
					this._Criatura_ValorPX = value;
					this.SendPropertyChanged("Criatura_ValorPX");
					this.OnCriatura_ValorPXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Criatura_DG", DbType="Int")]
		public System.Nullable<int> Criatura_DG
		{
			get
			{
				return this._Criatura_DG;
			}
			set
			{
				if ((this._Criatura_DG != value))
				{
					this.OnCriatura_DGChanging(value);
					this.SendPropertyChanging();
					this._Criatura_DG = value;
					this.SendPropertyChanged("Criatura_DG");
					this.OnCriatura_DGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Criatura_Habilidades_I", DbType="NVarChar(100)")]
		public string Criatura_Habilidades_I
		{
			get
			{
				return this._Criatura_Habilidades_I;
			}
			set
			{
				if ((this._Criatura_Habilidades_I != value))
				{
					this.OnCriatura_Habilidades_IChanging(value);
					this.SendPropertyChanging();
					this._Criatura_Habilidades_I = value;
					this.SendPropertyChanged("Criatura_Habilidades_I");
					this.OnCriatura_Habilidades_IChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Criatura_Habilidades_II", DbType="NVarChar(100)")]
		public string Criatura_Habilidades_II
		{
			get
			{
				return this._Criatura_Habilidades_II;
			}
			set
			{
				if ((this._Criatura_Habilidades_II != value))
				{
					this.OnCriatura_Habilidades_IIChanging(value);
					this.SendPropertyChanging();
					this._Criatura_Habilidades_II = value;
					this.SendPropertyChanged("Criatura_Habilidades_II");
					this.OnCriatura_Habilidades_IIChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class CriaturasPersonalizadas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Criatura_Nombre;
		
		private System.Nullable<long> _Criatura_CA_Neg;
		
		private System.Nullable<long> _Criatura_CA_Pos;
		
		private System.Nullable<long> _Criatura_Vida_Media;
		
		private System.Nullable<long> _Criatura_Vida_Max;
		
		private System.Nullable<long> _Criatura_Ataque;
		
		private string _Criatura_Ataque_I;
		
		private string _Criatura_Ataque_II;
		
		private System.Nullable<long> _Criatura_S_VenMuer;
		
		private System.Nullable<long> _Criatura_S_Varitas;
		
		private System.Nullable<long> _Criatura_S_PetrifParal;
		
		private System.Nullable<long> _Criatura_S_AlienDrag;
		
		private System.Nullable<long> _Criatura_S_Sortilegios;
		
		private System.Nullable<long> _Criatura_Mov;
		
		private System.Nullable<long> _Criatura_Moral;
		
		private System.Nullable<long> _Criatura_ValorTesoro;
		
		private string _Criatura_Alineam;
		
		private System.Nullable<long> _Criatura_ValorPX;
		
		private System.Nullable<long> _Criatura_DG;
		
		private string _Criatura_Habilidades_I;
		
		private string _Criatura_Habilidades_II;
		
		private string _Criatura_Ruta;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCriatura_NombreChanging(string value);
    partial void OnCriatura_NombreChanged();
    partial void OnCriatura_CA_NegChanging(System.Nullable<long> value);
    partial void OnCriatura_CA_NegChanged();
    partial void OnCriatura_CA_PosChanging(System.Nullable<long> value);
    partial void OnCriatura_CA_PosChanged();
    partial void OnCriatura_Vida_MediaChanging(System.Nullable<long> value);
    partial void OnCriatura_Vida_MediaChanged();
    partial void OnCriatura_Vida_MaxChanging(System.Nullable<long> value);
    partial void OnCriatura_Vida_MaxChanged();
    partial void OnCriatura_AtaqueChanging(System.Nullable<long> value);
    partial void OnCriatura_AtaqueChanged();
    partial void OnCriatura_Ataque_IChanging(string value);
    partial void OnCriatura_Ataque_IChanged();
    partial void OnCriatura_Ataque_IIChanging(string value);
    partial void OnCriatura_Ataque_IIChanged();
    partial void OnCriatura_S_VenMuerChanging(System.Nullable<long> value);
    partial void OnCriatura_S_VenMuerChanged();
    partial void OnCriatura_S_VaritasChanging(System.Nullable<long> value);
    partial void OnCriatura_S_VaritasChanged();
    partial void OnCriatura_S_PetrifParalChanging(System.Nullable<long> value);
    partial void OnCriatura_S_PetrifParalChanged();
    partial void OnCriatura_S_AlienDragChanging(System.Nullable<long> value);
    partial void OnCriatura_S_AlienDragChanged();
    partial void OnCriatura_S_SortilegiosChanging(System.Nullable<long> value);
    partial void OnCriatura_S_SortilegiosChanged();
    partial void OnCriatura_MovChanging(System.Nullable<long> value);
    partial void OnCriatura_MovChanged();
    partial void OnCriatura_MoralChanging(System.Nullable<long> value);
    partial void OnCriatura_MoralChanged();
    partial void OnCriatura_ValorTesoroChanging(System.Nullable<long> value);
    partial void OnCriatura_ValorTesoroChanged();
    partial void OnCriatura_AlineamChanging(string value);
    partial void OnCriatura_AlineamChanged();
    partial void OnCriatura_ValorPXChanging(System.Nullable<long> value);
    partial void OnCriatura_ValorPXChanged();
    partial void OnCriatura_DGChanging(System.Nullable<long> value);
    partial void OnCriatura_DGChanged();
    partial void OnCriatura_Habilidades_IChanging(string value);
    partial void OnCriatura_Habilidades_IChanged();
    partial void OnCriatura_Habilidades_IIChanging(string value);
    partial void OnCriatura_Habilidades_IIChanged();
    partial void OnCriatura_RutaChanging(string value);
    partial void OnCriatura_RutaChanged();
    #endregion
		
		public CriaturasPersonalizadas()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Criatura_Nombre", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Criatura_Nombre
		{
			get
			{
				return this._Criatura_Nombre;
			}
			set
			{
				if ((this._Criatura_Nombre != value))
				{
					this.OnCriatura_NombreChanging(value);
					this.SendPropertyChanging();
					this._Criatura_Nombre = value;
					this.SendPropertyChanged("Criatura_Nombre");
					this.OnCriatura_NombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Criatura_CA_Neg", DbType="BigInt")]
		public System.Nullable<long> Criatura_CA_Neg
		{
			get
			{
				return this._Criatura_CA_Neg;
			}
			set
			{
				if ((this._Criatura_CA_Neg != value))
				{
					this.OnCriatura_CA_NegChanging(value);
					this.SendPropertyChanging();
					this._Criatura_CA_Neg = value;
					this.SendPropertyChanged("Criatura_CA_Neg");
					this.OnCriatura_CA_NegChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Criatura_CA_Pos", DbType="BigInt")]
		public System.Nullable<long> Criatura_CA_Pos
		{
			get
			{
				return this._Criatura_CA_Pos;
			}
			set
			{
				if ((this._Criatura_CA_Pos != value))
				{
					this.OnCriatura_CA_PosChanging(value);
					this.SendPropertyChanging();
					this._Criatura_CA_Pos = value;
					this.SendPropertyChanged("Criatura_CA_Pos");
					this.OnCriatura_CA_PosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Criatura_Vida_Media", DbType="BigInt")]
		public System.Nullable<long> Criatura_Vida_Media
		{
			get
			{
				return this._Criatura_Vida_Media;
			}
			set
			{
				if ((this._Criatura_Vida_Media != value))
				{
					this.OnCriatura_Vida_MediaChanging(value);
					this.SendPropertyChanging();
					this._Criatura_Vida_Media = value;
					this.SendPropertyChanged("Criatura_Vida_Media");
					this.OnCriatura_Vida_MediaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Criatura_Vida_Max", DbType="BigInt")]
		public System.Nullable<long> Criatura_Vida_Max
		{
			get
			{
				return this._Criatura_Vida_Max;
			}
			set
			{
				if ((this._Criatura_Vida_Max != value))
				{
					this.OnCriatura_Vida_MaxChanging(value);
					this.SendPropertyChanging();
					this._Criatura_Vida_Max = value;
					this.SendPropertyChanged("Criatura_Vida_Max");
					this.OnCriatura_Vida_MaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Criatura_Ataque", DbType="BigInt")]
		public System.Nullable<long> Criatura_Ataque
		{
			get
			{
				return this._Criatura_Ataque;
			}
			set
			{
				if ((this._Criatura_Ataque != value))
				{
					this.OnCriatura_AtaqueChanging(value);
					this.SendPropertyChanging();
					this._Criatura_Ataque = value;
					this.SendPropertyChanged("Criatura_Ataque");
					this.OnCriatura_AtaqueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Criatura_Ataque_I", DbType="NVarChar(100)")]
		public string Criatura_Ataque_I
		{
			get
			{
				return this._Criatura_Ataque_I;
			}
			set
			{
				if ((this._Criatura_Ataque_I != value))
				{
					this.OnCriatura_Ataque_IChanging(value);
					this.SendPropertyChanging();
					this._Criatura_Ataque_I = value;
					this.SendPropertyChanged("Criatura_Ataque_I");
					this.OnCriatura_Ataque_IChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Criatura_Ataque_II", DbType="NVarChar(100)")]
		public string Criatura_Ataque_II
		{
			get
			{
				return this._Criatura_Ataque_II;
			}
			set
			{
				if ((this._Criatura_Ataque_II != value))
				{
					this.OnCriatura_Ataque_IIChanging(value);
					this.SendPropertyChanging();
					this._Criatura_Ataque_II = value;
					this.SendPropertyChanged("Criatura_Ataque_II");
					this.OnCriatura_Ataque_IIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Criatura_S_VenMuer", DbType="BigInt")]
		public System.Nullable<long> Criatura_S_VenMuer
		{
			get
			{
				return this._Criatura_S_VenMuer;
			}
			set
			{
				if ((this._Criatura_S_VenMuer != value))
				{
					this.OnCriatura_S_VenMuerChanging(value);
					this.SendPropertyChanging();
					this._Criatura_S_VenMuer = value;
					this.SendPropertyChanged("Criatura_S_VenMuer");
					this.OnCriatura_S_VenMuerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Criatura_S_Varitas", DbType="BigInt")]
		public System.Nullable<long> Criatura_S_Varitas
		{
			get
			{
				return this._Criatura_S_Varitas;
			}
			set
			{
				if ((this._Criatura_S_Varitas != value))
				{
					this.OnCriatura_S_VaritasChanging(value);
					this.SendPropertyChanging();
					this._Criatura_S_Varitas = value;
					this.SendPropertyChanged("Criatura_S_Varitas");
					this.OnCriatura_S_VaritasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Criatura_S_PetrifParal", DbType="BigInt")]
		public System.Nullable<long> Criatura_S_PetrifParal
		{
			get
			{
				return this._Criatura_S_PetrifParal;
			}
			set
			{
				if ((this._Criatura_S_PetrifParal != value))
				{
					this.OnCriatura_S_PetrifParalChanging(value);
					this.SendPropertyChanging();
					this._Criatura_S_PetrifParal = value;
					this.SendPropertyChanged("Criatura_S_PetrifParal");
					this.OnCriatura_S_PetrifParalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Criatura_S_AlienDrag", DbType="BigInt")]
		public System.Nullable<long> Criatura_S_AlienDrag
		{
			get
			{
				return this._Criatura_S_AlienDrag;
			}
			set
			{
				if ((this._Criatura_S_AlienDrag != value))
				{
					this.OnCriatura_S_AlienDragChanging(value);
					this.SendPropertyChanging();
					this._Criatura_S_AlienDrag = value;
					this.SendPropertyChanged("Criatura_S_AlienDrag");
					this.OnCriatura_S_AlienDragChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Criatura_S_Sortilegios", DbType="BigInt")]
		public System.Nullable<long> Criatura_S_Sortilegios
		{
			get
			{
				return this._Criatura_S_Sortilegios;
			}
			set
			{
				if ((this._Criatura_S_Sortilegios != value))
				{
					this.OnCriatura_S_SortilegiosChanging(value);
					this.SendPropertyChanging();
					this._Criatura_S_Sortilegios = value;
					this.SendPropertyChanged("Criatura_S_Sortilegios");
					this.OnCriatura_S_SortilegiosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Criatura_Mov", DbType="BigInt")]
		public System.Nullable<long> Criatura_Mov
		{
			get
			{
				return this._Criatura_Mov;
			}
			set
			{
				if ((this._Criatura_Mov != value))
				{
					this.OnCriatura_MovChanging(value);
					this.SendPropertyChanging();
					this._Criatura_Mov = value;
					this.SendPropertyChanged("Criatura_Mov");
					this.OnCriatura_MovChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Criatura_Moral", DbType="BigInt")]
		public System.Nullable<long> Criatura_Moral
		{
			get
			{
				return this._Criatura_Moral;
			}
			set
			{
				if ((this._Criatura_Moral != value))
				{
					this.OnCriatura_MoralChanging(value);
					this.SendPropertyChanging();
					this._Criatura_Moral = value;
					this.SendPropertyChanged("Criatura_Moral");
					this.OnCriatura_MoralChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Criatura_ValorTesoro", DbType="BigInt")]
		public System.Nullable<long> Criatura_ValorTesoro
		{
			get
			{
				return this._Criatura_ValorTesoro;
			}
			set
			{
				if ((this._Criatura_ValorTesoro != value))
				{
					this.OnCriatura_ValorTesoroChanging(value);
					this.SendPropertyChanging();
					this._Criatura_ValorTesoro = value;
					this.SendPropertyChanged("Criatura_ValorTesoro");
					this.OnCriatura_ValorTesoroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Criatura_Alineam", DbType="NVarChar(50)")]
		public string Criatura_Alineam
		{
			get
			{
				return this._Criatura_Alineam;
			}
			set
			{
				if ((this._Criatura_Alineam != value))
				{
					this.OnCriatura_AlineamChanging(value);
					this.SendPropertyChanging();
					this._Criatura_Alineam = value;
					this.SendPropertyChanged("Criatura_Alineam");
					this.OnCriatura_AlineamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Criatura_ValorPX", DbType="BigInt")]
		public System.Nullable<long> Criatura_ValorPX
		{
			get
			{
				return this._Criatura_ValorPX;
			}
			set
			{
				if ((this._Criatura_ValorPX != value))
				{
					this.OnCriatura_ValorPXChanging(value);
					this.SendPropertyChanging();
					this._Criatura_ValorPX = value;
					this.SendPropertyChanged("Criatura_ValorPX");
					this.OnCriatura_ValorPXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Criatura_DG", DbType="BigInt")]
		public System.Nullable<long> Criatura_DG
		{
			get
			{
				return this._Criatura_DG;
			}
			set
			{
				if ((this._Criatura_DG != value))
				{
					this.OnCriatura_DGChanging(value);
					this.SendPropertyChanging();
					this._Criatura_DG = value;
					this.SendPropertyChanged("Criatura_DG");
					this.OnCriatura_DGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Criatura_Habilidades_I", DbType="NVarChar(100)")]
		public string Criatura_Habilidades_I
		{
			get
			{
				return this._Criatura_Habilidades_I;
			}
			set
			{
				if ((this._Criatura_Habilidades_I != value))
				{
					this.OnCriatura_Habilidades_IChanging(value);
					this.SendPropertyChanging();
					this._Criatura_Habilidades_I = value;
					this.SendPropertyChanged("Criatura_Habilidades_I");
					this.OnCriatura_Habilidades_IChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Criatura_Habilidades_II", DbType="NVarChar(100)")]
		public string Criatura_Habilidades_II
		{
			get
			{
				return this._Criatura_Habilidades_II;
			}
			set
			{
				if ((this._Criatura_Habilidades_II != value))
				{
					this.OnCriatura_Habilidades_IIChanging(value);
					this.SendPropertyChanging();
					this._Criatura_Habilidades_II = value;
					this.SendPropertyChanged("Criatura_Habilidades_II");
					this.OnCriatura_Habilidades_IIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Criatura_Ruta", DbType="NVarChar(200)")]
		public string Criatura_Ruta
		{
			get
			{
				return this._Criatura_Ruta;
			}
			set
			{
				if ((this._Criatura_Ruta != value))
				{
					this.OnCriatura_RutaChanging(value);
					this.SendPropertyChanging();
					this._Criatura_Ruta = value;
					this.SendPropertyChanged("Criatura_Ruta");
					this.OnCriatura_RutaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class Equipo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Equipo_Id;
		
		private string _Equipo_Nombre;
		
		private System.Nullable<long> _Equipo_Coste;
		
		private System.Nullable<double> _Equipo_Peso;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEquipo_IdChanging(int value);
    partial void OnEquipo_IdChanged();
    partial void OnEquipo_NombreChanging(string value);
    partial void OnEquipo_NombreChanged();
    partial void OnEquipo_CosteChanging(System.Nullable<long> value);
    partial void OnEquipo_CosteChanged();
    partial void OnEquipo_PesoChanging(System.Nullable<double> value);
    partial void OnEquipo_PesoChanged();
    #endregion
		
		public Equipo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Equipo_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Equipo_Id
		{
			get
			{
				return this._Equipo_Id;
			}
			set
			{
				if ((this._Equipo_Id != value))
				{
					this.OnEquipo_IdChanging(value);
					this.SendPropertyChanging();
					this._Equipo_Id = value;
					this.SendPropertyChanged("Equipo_Id");
					this.OnEquipo_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Equipo_Nombre", DbType="NVarChar(50)")]
		public string Equipo_Nombre
		{
			get
			{
				return this._Equipo_Nombre;
			}
			set
			{
				if ((this._Equipo_Nombre != value))
				{
					this.OnEquipo_NombreChanging(value);
					this.SendPropertyChanging();
					this._Equipo_Nombre = value;
					this.SendPropertyChanged("Equipo_Nombre");
					this.OnEquipo_NombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Equipo_Coste", DbType="BigInt")]
		public System.Nullable<long> Equipo_Coste
		{
			get
			{
				return this._Equipo_Coste;
			}
			set
			{
				if ((this._Equipo_Coste != value))
				{
					this.OnEquipo_CosteChanging(value);
					this.SendPropertyChanging();
					this._Equipo_Coste = value;
					this.SendPropertyChanged("Equipo_Coste");
					this.OnEquipo_CosteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Equipo_Peso", DbType="Float")]
		public System.Nullable<double> Equipo_Peso
		{
			get
			{
				return this._Equipo_Peso;
			}
			set
			{
				if ((this._Equipo_Peso != value))
				{
					this.OnEquipo_PesoChanging(value);
					this.SendPropertyChanging();
					this._Equipo_Peso = value;
					this.SendPropertyChanged("Equipo_Peso");
					this.OnEquipo_PesoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class Lugares : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Lugar_Id;
		
		private string _Lugar_Nombre;
		
		private System.Data.Linq.Binary _Lugar_Imagen;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLugar_IdChanging(int value);
    partial void OnLugar_IdChanged();
    partial void OnLugar_NombreChanging(string value);
    partial void OnLugar_NombreChanged();
    partial void OnLugar_ImagenChanging(System.Data.Linq.Binary value);
    partial void OnLugar_ImagenChanged();
    #endregion
		
		public Lugares()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lugar_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Lugar_Id
		{
			get
			{
				return this._Lugar_Id;
			}
			set
			{
				if ((this._Lugar_Id != value))
				{
					this.OnLugar_IdChanging(value);
					this.SendPropertyChanging();
					this._Lugar_Id = value;
					this.SendPropertyChanged("Lugar_Id");
					this.OnLugar_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lugar_Nombre", DbType="NVarChar(100)")]
		public string Lugar_Nombre
		{
			get
			{
				return this._Lugar_Nombre;
			}
			set
			{
				if ((this._Lugar_Nombre != value))
				{
					this.OnLugar_NombreChanging(value);
					this.SendPropertyChanging();
					this._Lugar_Nombre = value;
					this.SendPropertyChanged("Lugar_Nombre");
					this.OnLugar_NombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lugar_Imagen", DbType="Image", CanBeNull=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Lugar_Imagen
		{
			get
			{
				return this._Lugar_Imagen;
			}
			set
			{
				if ((this._Lugar_Imagen != value))
				{
					this.OnLugar_ImagenChanging(value);
					this.SendPropertyChanging();
					this._Lugar_Imagen = value;
					this.SendPropertyChanged("Lugar_Imagen");
					this.OnLugar_ImagenChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class Pnj : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Pnj_Nombre;
		
		private string _Pnj_Clase;
		
		private System.Nullable<long> _Pnj_Nivel;
		
		private string _Pnj_Alineamiento;
		
		private string _Pnj_Arma;
		
		private string _Pnj_Armadura;
		
		private string _Pnj_Escudo;
		
		private System.Nullable<long> _Pnj_CA_Neg;
		
		private System.Nullable<long> _Pnj_CA_Pos;
		
		private System.Nullable<long> _Pnj_Vida_Med;
		
		private System.Nullable<long> _Pnj_Vida_Max;
		
		private string _Pnj_Ataque_Arma;
		
		private System.Nullable<long> _Pnj_Ataque;
		
		private System.Nullable<long> _Pnj_S_Veneno;
		
		private System.Nullable<long> _Pnj_S_Varitas;
		
		private System.Nullable<long> _Pnj_S_Petrif;
		
		private System.Nullable<long> _Pnj_S_AliDrag;
		
		private System.Nullable<long> _Pnj_S_Sorti;
		
		private System.Nullable<long> _Pnj_PX;
		
		private System.Nullable<long> _Pnj_Mov;
		
		private System.Nullable<long> _Pnj_Tesoro;
		
		private string _Pnj_Texto;
		
		private string _Pnj_Ruta;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPnj_NombreChanging(string value);
    partial void OnPnj_NombreChanged();
    partial void OnPnj_ClaseChanging(string value);
    partial void OnPnj_ClaseChanged();
    partial void OnPnj_NivelChanging(System.Nullable<long> value);
    partial void OnPnj_NivelChanged();
    partial void OnPnj_AlineamientoChanging(string value);
    partial void OnPnj_AlineamientoChanged();
    partial void OnPnj_ArmaChanging(string value);
    partial void OnPnj_ArmaChanged();
    partial void OnPnj_ArmaduraChanging(string value);
    partial void OnPnj_ArmaduraChanged();
    partial void OnPnj_EscudoChanging(string value);
    partial void OnPnj_EscudoChanged();
    partial void OnPnj_CA_NegChanging(System.Nullable<long> value);
    partial void OnPnj_CA_NegChanged();
    partial void OnPnj_CA_PosChanging(System.Nullable<long> value);
    partial void OnPnj_CA_PosChanged();
    partial void OnPnj_Vida_MedChanging(System.Nullable<long> value);
    partial void OnPnj_Vida_MedChanged();
    partial void OnPnj_Vida_MaxChanging(System.Nullable<long> value);
    partial void OnPnj_Vida_MaxChanged();
    partial void OnPnj_Ataque_ArmaChanging(string value);
    partial void OnPnj_Ataque_ArmaChanged();
    partial void OnPnj_AtaqueChanging(System.Nullable<long> value);
    partial void OnPnj_AtaqueChanged();
    partial void OnPnj_S_VenenoChanging(System.Nullable<long> value);
    partial void OnPnj_S_VenenoChanged();
    partial void OnPnj_S_VaritasChanging(System.Nullable<long> value);
    partial void OnPnj_S_VaritasChanged();
    partial void OnPnj_S_PetrifChanging(System.Nullable<long> value);
    partial void OnPnj_S_PetrifChanged();
    partial void OnPnj_S_AliDragChanging(System.Nullable<long> value);
    partial void OnPnj_S_AliDragChanged();
    partial void OnPnj_S_SortiChanging(System.Nullable<long> value);
    partial void OnPnj_S_SortiChanged();
    partial void OnPnj_PXChanging(System.Nullable<long> value);
    partial void OnPnj_PXChanged();
    partial void OnPnj_MovChanging(System.Nullable<long> value);
    partial void OnPnj_MovChanged();
    partial void OnPnj_TesoroChanging(System.Nullable<long> value);
    partial void OnPnj_TesoroChanged();
    partial void OnPnj_TextoChanging(string value);
    partial void OnPnj_TextoChanged();
    partial void OnPnj_RutaChanging(string value);
    partial void OnPnj_RutaChanged();
    #endregion
		
		public Pnj()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pnj_Nombre", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Pnj_Nombre
		{
			get
			{
				return this._Pnj_Nombre;
			}
			set
			{
				if ((this._Pnj_Nombre != value))
				{
					this.OnPnj_NombreChanging(value);
					this.SendPropertyChanging();
					this._Pnj_Nombre = value;
					this.SendPropertyChanged("Pnj_Nombre");
					this.OnPnj_NombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pnj_Clase", DbType="NVarChar(100)")]
		public string Pnj_Clase
		{
			get
			{
				return this._Pnj_Clase;
			}
			set
			{
				if ((this._Pnj_Clase != value))
				{
					this.OnPnj_ClaseChanging(value);
					this.SendPropertyChanging();
					this._Pnj_Clase = value;
					this.SendPropertyChanged("Pnj_Clase");
					this.OnPnj_ClaseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pnj_Nivel", DbType="BigInt")]
		public System.Nullable<long> Pnj_Nivel
		{
			get
			{
				return this._Pnj_Nivel;
			}
			set
			{
				if ((this._Pnj_Nivel != value))
				{
					this.OnPnj_NivelChanging(value);
					this.SendPropertyChanging();
					this._Pnj_Nivel = value;
					this.SendPropertyChanged("Pnj_Nivel");
					this.OnPnj_NivelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pnj_Alineamiento", DbType="NVarChar(100)")]
		public string Pnj_Alineamiento
		{
			get
			{
				return this._Pnj_Alineamiento;
			}
			set
			{
				if ((this._Pnj_Alineamiento != value))
				{
					this.OnPnj_AlineamientoChanging(value);
					this.SendPropertyChanging();
					this._Pnj_Alineamiento = value;
					this.SendPropertyChanged("Pnj_Alineamiento");
					this.OnPnj_AlineamientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pnj_Arma", DbType="NVarChar(100)")]
		public string Pnj_Arma
		{
			get
			{
				return this._Pnj_Arma;
			}
			set
			{
				if ((this._Pnj_Arma != value))
				{
					this.OnPnj_ArmaChanging(value);
					this.SendPropertyChanging();
					this._Pnj_Arma = value;
					this.SendPropertyChanged("Pnj_Arma");
					this.OnPnj_ArmaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pnj_Armadura", DbType="NVarChar(100)")]
		public string Pnj_Armadura
		{
			get
			{
				return this._Pnj_Armadura;
			}
			set
			{
				if ((this._Pnj_Armadura != value))
				{
					this.OnPnj_ArmaduraChanging(value);
					this.SendPropertyChanging();
					this._Pnj_Armadura = value;
					this.SendPropertyChanged("Pnj_Armadura");
					this.OnPnj_ArmaduraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pnj_Escudo", DbType="NVarChar(100)")]
		public string Pnj_Escudo
		{
			get
			{
				return this._Pnj_Escudo;
			}
			set
			{
				if ((this._Pnj_Escudo != value))
				{
					this.OnPnj_EscudoChanging(value);
					this.SendPropertyChanging();
					this._Pnj_Escudo = value;
					this.SendPropertyChanged("Pnj_Escudo");
					this.OnPnj_EscudoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pnj_CA_Neg", DbType="BigInt")]
		public System.Nullable<long> Pnj_CA_Neg
		{
			get
			{
				return this._Pnj_CA_Neg;
			}
			set
			{
				if ((this._Pnj_CA_Neg != value))
				{
					this.OnPnj_CA_NegChanging(value);
					this.SendPropertyChanging();
					this._Pnj_CA_Neg = value;
					this.SendPropertyChanged("Pnj_CA_Neg");
					this.OnPnj_CA_NegChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pnj_CA_Pos", DbType="BigInt")]
		public System.Nullable<long> Pnj_CA_Pos
		{
			get
			{
				return this._Pnj_CA_Pos;
			}
			set
			{
				if ((this._Pnj_CA_Pos != value))
				{
					this.OnPnj_CA_PosChanging(value);
					this.SendPropertyChanging();
					this._Pnj_CA_Pos = value;
					this.SendPropertyChanged("Pnj_CA_Pos");
					this.OnPnj_CA_PosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pnj_Vida_Med", DbType="BigInt")]
		public System.Nullable<long> Pnj_Vida_Med
		{
			get
			{
				return this._Pnj_Vida_Med;
			}
			set
			{
				if ((this._Pnj_Vida_Med != value))
				{
					this.OnPnj_Vida_MedChanging(value);
					this.SendPropertyChanging();
					this._Pnj_Vida_Med = value;
					this.SendPropertyChanged("Pnj_Vida_Med");
					this.OnPnj_Vida_MedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pnj_Vida_Max", DbType="BigInt")]
		public System.Nullable<long> Pnj_Vida_Max
		{
			get
			{
				return this._Pnj_Vida_Max;
			}
			set
			{
				if ((this._Pnj_Vida_Max != value))
				{
					this.OnPnj_Vida_MaxChanging(value);
					this.SendPropertyChanging();
					this._Pnj_Vida_Max = value;
					this.SendPropertyChanged("Pnj_Vida_Max");
					this.OnPnj_Vida_MaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pnj_Ataque_Arma", DbType="NVarChar(50)")]
		public string Pnj_Ataque_Arma
		{
			get
			{
				return this._Pnj_Ataque_Arma;
			}
			set
			{
				if ((this._Pnj_Ataque_Arma != value))
				{
					this.OnPnj_Ataque_ArmaChanging(value);
					this.SendPropertyChanging();
					this._Pnj_Ataque_Arma = value;
					this.SendPropertyChanged("Pnj_Ataque_Arma");
					this.OnPnj_Ataque_ArmaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pnj_Ataque", DbType="BigInt")]
		public System.Nullable<long> Pnj_Ataque
		{
			get
			{
				return this._Pnj_Ataque;
			}
			set
			{
				if ((this._Pnj_Ataque != value))
				{
					this.OnPnj_AtaqueChanging(value);
					this.SendPropertyChanging();
					this._Pnj_Ataque = value;
					this.SendPropertyChanged("Pnj_Ataque");
					this.OnPnj_AtaqueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pnj_S_Veneno", DbType="BigInt")]
		public System.Nullable<long> Pnj_S_Veneno
		{
			get
			{
				return this._Pnj_S_Veneno;
			}
			set
			{
				if ((this._Pnj_S_Veneno != value))
				{
					this.OnPnj_S_VenenoChanging(value);
					this.SendPropertyChanging();
					this._Pnj_S_Veneno = value;
					this.SendPropertyChanged("Pnj_S_Veneno");
					this.OnPnj_S_VenenoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pnj_S_Varitas", DbType="BigInt")]
		public System.Nullable<long> Pnj_S_Varitas
		{
			get
			{
				return this._Pnj_S_Varitas;
			}
			set
			{
				if ((this._Pnj_S_Varitas != value))
				{
					this.OnPnj_S_VaritasChanging(value);
					this.SendPropertyChanging();
					this._Pnj_S_Varitas = value;
					this.SendPropertyChanged("Pnj_S_Varitas");
					this.OnPnj_S_VaritasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pnj_S_Petrif", DbType="BigInt")]
		public System.Nullable<long> Pnj_S_Petrif
		{
			get
			{
				return this._Pnj_S_Petrif;
			}
			set
			{
				if ((this._Pnj_S_Petrif != value))
				{
					this.OnPnj_S_PetrifChanging(value);
					this.SendPropertyChanging();
					this._Pnj_S_Petrif = value;
					this.SendPropertyChanged("Pnj_S_Petrif");
					this.OnPnj_S_PetrifChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pnj_S_AliDrag", DbType="BigInt")]
		public System.Nullable<long> Pnj_S_AliDrag
		{
			get
			{
				return this._Pnj_S_AliDrag;
			}
			set
			{
				if ((this._Pnj_S_AliDrag != value))
				{
					this.OnPnj_S_AliDragChanging(value);
					this.SendPropertyChanging();
					this._Pnj_S_AliDrag = value;
					this.SendPropertyChanged("Pnj_S_AliDrag");
					this.OnPnj_S_AliDragChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pnj_S_Sorti", DbType="BigInt")]
		public System.Nullable<long> Pnj_S_Sorti
		{
			get
			{
				return this._Pnj_S_Sorti;
			}
			set
			{
				if ((this._Pnj_S_Sorti != value))
				{
					this.OnPnj_S_SortiChanging(value);
					this.SendPropertyChanging();
					this._Pnj_S_Sorti = value;
					this.SendPropertyChanged("Pnj_S_Sorti");
					this.OnPnj_S_SortiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pnj_PX", DbType="BigInt")]
		public System.Nullable<long> Pnj_PX
		{
			get
			{
				return this._Pnj_PX;
			}
			set
			{
				if ((this._Pnj_PX != value))
				{
					this.OnPnj_PXChanging(value);
					this.SendPropertyChanging();
					this._Pnj_PX = value;
					this.SendPropertyChanged("Pnj_PX");
					this.OnPnj_PXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pnj_Mov", DbType="BigInt")]
		public System.Nullable<long> Pnj_Mov
		{
			get
			{
				return this._Pnj_Mov;
			}
			set
			{
				if ((this._Pnj_Mov != value))
				{
					this.OnPnj_MovChanging(value);
					this.SendPropertyChanging();
					this._Pnj_Mov = value;
					this.SendPropertyChanged("Pnj_Mov");
					this.OnPnj_MovChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pnj_Tesoro", DbType="BigInt")]
		public System.Nullable<long> Pnj_Tesoro
		{
			get
			{
				return this._Pnj_Tesoro;
			}
			set
			{
				if ((this._Pnj_Tesoro != value))
				{
					this.OnPnj_TesoroChanging(value);
					this.SendPropertyChanging();
					this._Pnj_Tesoro = value;
					this.SendPropertyChanged("Pnj_Tesoro");
					this.OnPnj_TesoroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pnj_Texto", DbType="NVarChar(200)")]
		public string Pnj_Texto
		{
			get
			{
				return this._Pnj_Texto;
			}
			set
			{
				if ((this._Pnj_Texto != value))
				{
					this.OnPnj_TextoChanging(value);
					this.SendPropertyChanging();
					this._Pnj_Texto = value;
					this.SendPropertyChanged("Pnj_Texto");
					this.OnPnj_TextoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pnj_Ruta", DbType="NVarChar(200)")]
		public string Pnj_Ruta
		{
			get
			{
				return this._Pnj_Ruta;
			}
			set
			{
				if ((this._Pnj_Ruta != value))
				{
					this.OnPnj_RutaChanging(value);
					this.SendPropertyChanging();
					this._Pnj_Ruta = value;
					this.SendPropertyChanged("Pnj_Ruta");
					this.OnPnj_RutaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class Transporte : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Transporte_Id;
		
		private string _Transporte_Nombre;
		
		private System.Nullable<long> _Transporte_Coste;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTransporte_IdChanging(int value);
    partial void OnTransporte_IdChanged();
    partial void OnTransporte_NombreChanging(string value);
    partial void OnTransporte_NombreChanged();
    partial void OnTransporte_CosteChanging(System.Nullable<long> value);
    partial void OnTransporte_CosteChanged();
    #endregion
		
		public Transporte()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Transporte_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Transporte_Id
		{
			get
			{
				return this._Transporte_Id;
			}
			set
			{
				if ((this._Transporte_Id != value))
				{
					this.OnTransporte_IdChanging(value);
					this.SendPropertyChanging();
					this._Transporte_Id = value;
					this.SendPropertyChanged("Transporte_Id");
					this.OnTransporte_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Transporte_Nombre", DbType="NVarChar(50)")]
		public string Transporte_Nombre
		{
			get
			{
				return this._Transporte_Nombre;
			}
			set
			{
				if ((this._Transporte_Nombre != value))
				{
					this.OnTransporte_NombreChanging(value);
					this.SendPropertyChanging();
					this._Transporte_Nombre = value;
					this.SendPropertyChanged("Transporte_Nombre");
					this.OnTransporte_NombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Transporte_Coste", DbType="BigInt")]
		public System.Nullable<long> Transporte_Coste
		{
			get
			{
				return this._Transporte_Coste;
			}
			set
			{
				if ((this._Transporte_Coste != value))
				{
					this.OnTransporte_CosteChanging(value);
					this.SendPropertyChanging();
					this._Transporte_Coste = value;
					this.SendPropertyChanged("Transporte_Coste");
					this.OnTransporte_CosteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
